# 第二次练习
## 练习题 1：数组创建与属性查看
**题目：** 使用 `arange()` 函数创建一个从 1 到 12 的一维等差数组，然后使用 `reshape()` 方法将其重塑为 3行4列的二维数组 。请分别打印出该数组的维度（`ndim`）、形状（`shape`）和元素总个数（`size`）。  

In [34]:
import numpy as np
arr = np.arange(1,13)  
arr = arr.reshape(3,4)
print("该数组：")
print(arr)
print("维度：",arr.ndim)
print("形状",arr.shape)
print("元素总个数：",arr.size)


该数组：
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
维度： 2
形状 (3, 4)
元素总个数： 12


### 练习题 2：数据类型转换
**题目：** 创建一个包含浮点数 `[1.5, 2.6, 3.7, 4.8]` 的 NumPy 数组。使用 `astype()` 方法将该数组的数据类型转换为 32位整数 (`np.int32`)，并打印转换前后的数组及其数据类型名称 (`dtype.name`) 。  

In [25]:
import numpy as np
arr = np.array([1.5, 2.6, 3.7, 4.8])
arr_int = arr.astype(np.int32)
print("转换前的数组：",arr)
print("转换前的数据类型：",arr.dtype.name)
print("转换后的数组：",arr_int)
print("转换后的数据类型：",arr_int.dtype.name)


转换前的数组： [1.5 2.6 3.7 4.8]
转换前的数据类型： float64
转换后的数组： [1 2 3 4]
转换后的数据类型： int32


### 练习题 3：二维数组的切片操作
**题目：** 创建一个二维数组 `arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])`。请使用切片操作获取原数组的前两行，以及第 2 到第 3 列的子数组（即期望得到 `[[2, 3], [6, 7]]`）。  

In [26]:
import numpy as np
arr = np.array([[1,2,3,4],
                [5,6,7,8],
                [9,10,11,12]])
sub_arr = arr[:2,1:3]
print("原数组")
print(arr)
print("子数组")
print(sub_arr)

原数组
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
子数组
[[2 3]
 [6 7]]


### 练习题 4：花式索引与布尔索引

**题目：** 给定一维数组 `arr = np.array([10, 15, 20, 25, 30, 35])`。

1. 使用花式索引提取第 1、3、5 个元素（即索引为 0, 2, 4 的元素）。  

2. 使用布尔索引提取数组中所有大于 20 的元素 。  

In [27]:
import numpy as np
arr = np.array([10, 15, 20, 25, 30, 35])
one_fancy_index_result = arr[[0, 2, 4]]
two_bool_index_result = arr[arr > 20]
print("1.",one_fancy_index_result)
print("2.",two_bool_index_result)


1. [10 20 30]
2. [25 30 35]


### 练习题 5：数组运算与广播机制
**题目：** 创建一个形状为 `(3, 4)` 的全 0 数组（使用 `zeros()` 函数）和一个一维数组 `arr_b = np.array([1, 2, 3, 4])` 。利用 NumPy 的广播机制，将这两个数组相加并打印出结果 。 

In [28]:
import numpy as np
arr_a = np.zeros((3, 4))
arr_b = np.array([1, 2, 3, 4])
result = arr_a + arr_b
print("相加结果：")
print(result)

相加结果：
[[1. 2. 3. 4.]
 [1. 2. 3. 4.]
 [1. 2. 3. 4.]]


### 练习题 6：通用函数的应用
**题目：** 给定数组 `x = np.array([1, 4, 9, 16])` 和 `y = np.array([2, 1, 4, 5])`。

1. 使用一元通用函数 `np.sqrt()` 计算数组 `x` 中每个元素的平方根 。  
2. 将得到的平方根数组与数组 `y` 结合，使用二元通用函数 `np.maximum()` 找出对应位置上的最大值 。 

In [29]:
import numpy as np
x = np.array([1, 4, 9, 16])
y = np.array([2, 1, 4, 5])
sqrt_x = np.sqrt(x)
max_result = np.maximum(sqrt_x, y)
print("x中每个元素的平方根：", sqrt_x)
print("对应位置上的最大值：", max_result)

x中每个元素的平方根： [1. 2. 3. 4.]
对应位置上的最大值： [2. 2. 4. 5.]


### 练习题 7：数组的转置
**题目：** 创建一个形状为 `(2, 3, 4)` 的三维数组 `arr = np.arange(24).reshape((2, 3, 4))` 。使用 `transpose()` 方法将该数组的轴顺序转换为 `(1, 0, 2)`，并打印转换后新数组的形状（`shape`） 。  

In [30]:
import numpy as np
arr = np.arange(24).reshape((2, 3, 4))
new_arr = arr.transpose((1, 0, 2))
print("原数组形状：", arr.shape)
print("转换后新数组形状：", new_arr.shape)

原数组形状： (2, 3, 4)
转换后新数组形状： (3, 2, 4)


### 练习题 8：条件逻辑运算
**题目：** 给出两个一维数组 `arr_x = np.array([1, 5, 7])`，`arr_y = np.array([2, 6, 8])` 以及一个布尔条件数组 `arr_con = np.array([True, False, True])` 。请使用 `np.where()` 函数，当条件为 `True` 时取 `arr_x` 中的对应元素，当条件为 `False` 时取 `arr_y` 中的对应元素 。  

In [31]:
import numpy as np
arr_x = np.array([1, 5, 7])
arr_y = np.array([2, 6, 8])
arr_con = np.array([True, False, True])
result = np.where(arr_con, arr_x, arr_y)
print("条件选择结果：", result)

条件选择结果： [1 6 7]


### 练习题 9：统计运算与排序
**题目：** 创建二维数组 `arr = np.array([[6, 2, 7], [3, 6, 2], [4, 3, 2]])` 。  
1. 使用统计方法计算该数组所有元素的算术平均值（`mean()`）。  
2. 使用 `sort()` 方法对该数组沿着 `axis=0` 的方向（按列顺序从小到大）进行排序，并打印排序后的结果 。  


In [32]:
import numpy as np
arr = np.array([[6, 2, 7],
                [3, 6, 2],
                [4, 3, 2]])
mean_result = arr.mean()

arr_sorted = arr.copy()
arr_sorted.sort(axis=0)
print("所有元素的算术平均值：", mean_result)
print("按列排序后的结果：")
print(arr_sorted)

所有元素的算术平均值： 3.888888888888889
按列排序后的结果：
[[3 2 2]
 [4 3 2]
 [6 6 7]]


### 练习题 10：随机数生成与矩阵点积
**题目：** 1. 设置随机数种子为 `10`（使用 `np.random.seed()` 保证每次生成的随机数一致）。 2. 使用随机数模块生成两个形状为 `(2, 2)` 且服从 [0, 1) 均匀分布的随机矩阵 A 和 B（使用 `np.random.rand()`）。 3. 使用线性代数模块的 `dot()` 方法计算矩阵 A 和矩阵 B 的点积 。  

In [33]:
import numpy as np
np.random.seed(10)
A = np.random.rand(2, 2)
B = np.random.rand(2, 2)
result = np.dot(A, B)
print("矩阵 A：")
print(A)
print("矩阵 B：")
print(B)
print("A 和 B 的点积：")
print(result)

矩阵 A：
[[0.77132064 0.02075195]
 [0.63364823 0.74880388]]
矩阵 B：
[[0.49850701 0.22479665]
 [0.19806286 0.76053071]]
A 和 B 的点积：
[[0.38861894 0.18917279]
 [0.46418833 0.71193035]]
